export const SOURCES = [
	{
		id: "piltover-archive",
		name: "Piltover Archive",
		url: "piltoverarchive.gg",
		description: "Community-curated deck database with advanced filtering and in-depth write-ups.",
		tags: ["Community", "Meta", "Guides"],
		accentColor: "#4a90d9",
		glowColor: "#4a90d944",
		icon: "🏛️",
		deckCount: "4,200+",
		status: "active",
	},
	{
		id: "riftdecks",
		name: "Riftdecks",
		url: "riftdecks.io",
		description: "Tournament lists and ranked ladder decklists updated weekly with meta snapshots.",
		tags: ["Tournament", "Ladder", "Meta"],
		accentColor: "#a855f7",
		glowColor: "#a855f744",
		icon: "⚔️",
		deckCount: "2,800+",
		status: "active",
	},
	{
		id: "the-vault",
		name: "The Vault",
		url: "riftbound-vault.com",
		description: "Player-submitted decklists with community ratings, comments, and video guides.",
		tags: ["Community", "Budget", "Brewing"],
		accentColor: "#e8d090",
		glowColor: "#e8d09044",
		icon: "🔒",
		deckCount: "9,100+",
		status: "active",
	},
	{
		id: "metawatch",
		name: "MetaWatch",
		url: "metawatch.gg",
		description: "Data-driven tier lists and win-rate analytics pulled from ranked play every 48 hours.",
		tags: ["Tier List", "Analytics", "Ranked"],
		accentColor: "#34d399",
		glowColor: "#34d39944",
		icon: "📊",
		deckCount: "Tier data",
		status: "active",
	},
];
